name: Daily LinkedIn Job Alert

on:
  schedule:
    - cron: '30 6 * * *'  # Runs every day at 12:00 PM IST
  workflow_dispatch:       # Allows manual trigger

jobs:
  send-job-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run job notifier script
        run: npm start
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TARGET_EMAIL: ${{ secrets.TARGET_EMAIL }}
